# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
en:
  languageCode: en-us
  contentDir: content/en
  title: José Luis Texcalac Sangrador
  params:
    description: English
  # Uncomment for multi-lingual sites, and move English content into `en` sub-folder.
  #contentDir: content/en

# Uncomment the lines below to configure your website in a second language.
es:
  languageCode: es
  contentDir: content/es
  title: José Luis Texcalac Sangrador
  params:
    description: Sitio en español
  menu:
    main:
      - name: es
        url: '#about'
        weight: 1
